#
# Copyright © 2021 ProStore
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM openjdk:8-jdk-slim
WORKDIR app
RUN mkdir config
ADD /target/dtm-status-monitor-*.jar dtm-status-monitor.jar
ENV STATUS_MONITOR_BROKERS=localhost:9092
ENV STATUS_MONITOR_CONSUMERS=8
ENV SERVER_PORT=9095
EXPOSE 9095
ENTRYPOINT ["java", "-Dspring.config.location=classpath:application.yml,config/application.yml", "-jar", "dtm-status-monitor.jar"]
